# Generated by Django 4.0.6 on 2022-08-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_kegiatan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
